changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: '🚀 Features'
      labels:
        - enhancement
        - feature
    - title: '🐛 Bug Fixes'
      labels:
        - bug
        - fix
    - title: '📝 Documentation'
      labels:
        - documentation
        - docs